### ISSUE TITLE
create frontend, backend run script

### ISSUE THREAD

**Issue by clarkngo** [codelab-internship-word-tracking-team/word-tracking-app#8]
Add script to run both frontend and backend

**Comment by t0ri** [comment]
Starting the backend with `sh ./run.sh` and requesting data returns `ECONNREFUSED`, regardless of how the GET was sent:
- directly fetch('http://localhost:3000/projects')
- proxy to 'http://localhost:3000' and then fetch('/projects')
- use Postman to GET `http://localhost:3000/projects`

Responses are functional when `node app.js` and `npm start` are run separately.
